Update/ad reporting v2
fivetran/dbt_facebook_ads pull request #21
Opened 2022-06-24 00:43 UTC by fivetran-sheringuyen

Pull Request
**Are you a current Fivetran customer?** 

**What change(s) does this PR introduce?** 

**Did you update the CHANGELOG?** 

- [ ] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [ ] No 

**How did you test the PR changes?** 

 

- [ ] CircleCi  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz requested changes
@fivetran-sheringuyen thanks so much for putting this PR together and taking on the mighty task of combining the creative history and this package! These updates are looking great, I do have a few comments I would like for you to address before approving the PR:

- [x] Address the inline comments within this review
- [x] I noticed in the end models the records can have a `null` record for clicks, but there are also records for `0`. This doesn't seem to be the same for `impressions` and `spend`. Should we convert these `null` records to be `0`? Or what is the difference between `null` and `0` clicks in this case?
- [x] Open a FR for us to integrate the remaining creative history models into this package. In the meantime within the FR we can point users to the creative history package to replicate the models in the meantime. 
- [x] I notice we don't have any tests or yml documentation for the creative history models. Can we port them over to ensure we are [still applying the same tests](https://github.com/fivetran/dbt_facebook_ads_creative_history/blob/main/models/facebook_backwards_compatibility.yml) we were previously.
- [ ] What is your stance on renaming the models that were moved from `dbt_facebook_ads_creative_history` to `stg_` instead of `int_`?
  - Since I could see people using them as staging models, I wonder if it would make more sense to name them as such, but obviously keep the logic in the transformation package.
  - Otherwise, what are your thoughts on making them final models that users can reference. Simply because I see these models being leveraged on their own, and it may be confusing to name them as intermediate. Thoughts?

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on DECISIONLOG.md
> +        - `utm_source`
You use `utm_source` twice here. Did you intend for it to be `utm_term`?

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on DECISIONLOG.md
> +# Decision Log
The format of this looks pretty weird. I think there must be some parsing issue that needs to be fixed in order for it to render in the way you are wanting.
![image](https://user-images.githubusercontent.com/74217849/175983649-391d9514-e27f-48f3-86a3-18a4f67cd5b8.png)

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on integration_tests/dbt_project.yml
>    +materialized: table
Do you know why we have this? Not sure if it is needed anymore 🤔

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on integration_tests/seeds/facebook_ads_ad_history_data.csv
> +id,account_id,ad_set_id,campaign_id,creative_id,name,updated_time
Same comment from the source about the reason for fully removing this field.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on macros/get_url_tag_query.sql
> +      select _fivetran_id, creative_id, url_tag_element
Super minor, but can we space these out the same way we typically do with selecting fields in a query.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on macros/get_url_tag_query.sql
> +      select _fivetran_id, creative_id, url_tag_element
Same comment for the other warehouse specific versions as well.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on models/facebook_ads__account_report.sql
> +        accounts.account_name,
Curious what your stance is on just including these fields in the final model. I could see a few other fields from the staging model being relevant to include here (currency, status, time_zone). What was your reasoning for just including these three?

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on models/facebook_ads__account_report.sql
> +        on cast(report.account_id as {{ dbt_utils.type_bigint() }}) = cast(accounts.account_id as {{ dbt_utils.type_bigint() }})
Can we do these datatype castings in the staging models instead? Also, is there any risk these fields could ever be of type strings?

Same comment for the other models as well.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_facebook_ads__creative_history.sql
>      where is_most_recent_record = true
If you move forward with changing the name of this field in the source package then we will want to adjust that here as well.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_facebook_ads__url_tags.sql
> +    where is_most_recent_record = true
Same comment about needing to change this field name if we rename in the source.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on packages.yml
> +    warn-unpinned: false
Just commenting to make sure we update on release 😄

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on README.md
> +By default, this package runs using your destination and the `facebook_ads` schema. If this is not where your Facebook Ads data is (for example, if your Facebook Ads schema is named `Facebook_ads_fiv
```suggestion
By default, this package runs using your destination and the `facebook_ads` schema. If this is not where your Facebook Ads data is (for example, if your Facebook Ads schema is named `facebook_ads_fivetran`), add the following configuration to your root `dbt_project.yml` file:
```

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on README.md
> +      version: [">=0.8.0", "<0.9.0"]
I think this should be in the range of 0.5.0 and 0.6.0.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz commented on README.md
> +# 🙌 How is this package maintained and can I contribute?
We should also add the reference to the DECISIONLOG.md in this section as well.

2022-06-28 19:39 UTC, fivetran-sheringuyen commented on integration_tests/dbt_project.yml
>    +materialized: table
Ah probably a holdover from the previous version, removing!

2022-06-28 19:44 UTC, fivetran-sheringuyen commented on models/facebook_ads__account_report.sql
> +        accounts.account_name,
Honestly, this kind of just slipped my mind. *Homer D'oh*. Let me go back and add some fields from staging!

2022-06-28 20:25 UTC, fivetran-sheringuyen commented on models/facebook_ads__account_report.sql
> +        on cast(report.account_id as {{ dbt_utils.type_bigint() }}) = cast(accounts.account_id as {{ dbt_utils.type_bigint() }})
Np, will migrate that. It _should_ always be an integer from what I can tell based on our data and [FB documentation](https://developers.facebook.com/docs/marketing-api/reference/ad-account#Reading)  says it should be a numeric string.

2022-06-28 21:02 UTC, fivetran-sheringuyen commented on models/intermediate/int_facebook_ads__creative_history.sql
>      where is_most_recent_record = true
Decided to revert to original logic!

2022-06-28 22:17 UTC, fivetran-sheringuyen commented
Hey @fivetran-joemarkiewicz, I've just committed the PR fixes you've requested, let me know if you want to discuss further!

Regarding your question:

> What is your stance on renaming the models that were moved from dbt_facebook_ads_creative_history to stg_ instead of int_?
> - Since I could see people using them as staging models, I wonder if it would make more sense to name them as such, but obviously keep the logic in the transformation package.
> - Otherwise, what are your thoughts on making them final models that users can reference. Simply because I see these models being leveraged on their own, and it may be confusing to name them as intermediate. Thoughts?

I agree that people could definitely use them so I think it would make sense to create them as their own final models. With the one model (`*_url_tags`) that we've migrated over in this update, I've made it into a final model and added appropriate testing for it in `facebook_ads.yml`.  

`int_facebook_ads__creative_history`, however, should be kept as an intermediate model -- it actually takes `*_url_tags` and prepares it for the `utm_report`. While we've transformed the data to fit for our specific modeling needs, these transformations may not scale across the user base. 

Additionally, as per our conversation last week, I believe we spoke about keeping 
```
  - package: fivetran/facebook_ads_creative_history
    version: [">=0.4.0", "<0.5.0"]
```
in the `packages.yml`, so I updated this as well. Let me know if your thoughts have changed on this front.

2022-06-29 20:41 UTC, fivetran-joemarkiewicz commented on packages.yml
> +  #   version: [">=0.4.0", "<0.5.0"]
We will also want to cut a release for this package then to have the new source package as a dependency on the updated source package.

2022-06-29 22:09 UTC, fivetran-joemarkiewicz approved these changes
Looks good to go!!! Thanks so much @fivetran-sheringuyen

2022-07-20 17:13 UTC, fivetran-sheringuyen commented
Running comments before merge:
- Add not_null tests to final model tests

2022-09-02 20:21 UTC, merged