Feature/add conversions
fivetran/dbt_facebook_ads pull request #43
Opened 2024-05-21 23:05 UTC by fivetran-jamie

## PR Overview
**This PR will address the following Issue/Feature:**
no issue made

**This PR will result in the following new package version:**

v0.8.0

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [x] dbt run –full-refresh && dbt test
- [ ] dbt run (if incremental models are present)

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked, tagged, and properly assigned
- [x] All necessary documentation and version upgrades have been applied
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)
- [x] BuildKite integration tests are passing
- [x] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

[Tests](https://github.com/fivetran/dbt_facebook_ads/tree/feature/add-conversions/integration_tests/tests) are passing
![image](https://github.com/fivetran/dbt_facebook_ads/assets/65564846/25ccb7a6-3f6a-49e7-bfa4-227137aa91b5)

1. Horizontal integrity test compares total sum of `conversion_value` from each `_report` end model 
2. Consistency tests compare `clicks`, `impressions`, and `spend` across dev and prod in each of the `_report` models

No exceptions needed, just a teeny tiny buffer to account for differences in rounding
![image](https://github.com/fivetran/dbt_facebook_ads/assets/65564846/b131f62a-bce2-4fe1-89a4-4cc64671d788)

2024-05-23 18:44 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-jamie these changes look great! I just have a few minor suggestions, but none related to the actual code. I see this being a huge value add for our users!

Once you address the comments in this review let's hold off merging until the other updates in the Google and LinkedIn packages are ready as well. Thanks and great job!

2024-05-23 18:44 UTC, fivetran-joemarkiewicz commented on integration_tests/dbt_project.yml
> +    - pattern: offsite_conversion%
You will need to add the following models config for the consistency validations to run properly.
```suggestion
    - pattern: offsite_conversion%
    
models:
  +schema: "facebook_ads_{{ var('directed_schema','dev') }}"
```

2024-05-23 18:44 UTC, fivetran-joemarkiewicz commented on packages.yml
> +  warn-unpinned: false
Reminder to swap before merge

2024-05-23 18:44 UTC, fivetran-joemarkiewicz commented on models/facebook_ads__account_report.sql
> +        , sum(coalesce(conversion_report.conversion_value, 0)) as conversion_value
Just to confirm, should 0 and `null` be represented the same here?

2024-05-23 18:44 UTC, fivetran-joemarkiewicz commented on models/facebook_ads__account_report.sql
> +        {% endif %}
What are your thoughts on consolidating this into a macro?

2024-05-23 18:44 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +  - By default, the package includes only the conversion value calculated using the default attribution window, but your report may include calculations using the other windows defined [here](https:/
Suggestion to not truncate variable
```suggestion
  - By default, the package includes only the conversion value calculated using the default attribution window, but your report may include calculations using the other windows defined [here](https://developers.facebook.com/docs/marketing-api/reference/ads-action-stats/). See [README](https://github.com/fivetran/dbt_facebook_ads_source/tree/main?tab=readme-ov-file#passing-through-additional-metrics) for details on how to use the new variable.
```

2024-05-23 18:44 UTC, fivetran-joemarkiewicz commented on README.md
> +| [facebook_ads__url_tags](https://fivetran.github.io/dbt_facebook_ads/#!/model/model.facebook_ads.facebook_ads__utm_report)            | Each record in this table is a unique combination of creative
Great catch!

2024-05-23 18:44 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- Updated the PR templates to align with our most up-to-date standards ([PR #43](https://github.com/fivetran/dbt_facebook_ads/pull/43)).
Not necessary for this initial review, but let's include a Contributors section here and make sure we give Seer a shout out. Will align more on what we should say once we chat with Seer.

2024-05-23 18:53 UTC, fivetran-catfritz commented
@fivetran-jamie @fivetran-joemarkiewicz Now might be a good time to delete the defunct [2nd reviewer bot](https://github.com/fivetran/dbt_facebook_ads/blob/main/.github/workflows/add-2nd-reviewer.yml).

2024-05-23 19:00 UTC, fivetran-joemarkiewicz commented
> @fivetran-jamie @fivetran-joemarkiewicz Now might be a good time to delete the defunct [2nd reviewer bot](https://github.com/fivetran/dbt_facebook_ads/blob/main/.github/workflows/add-2nd-reviewer.yml).

Agreed! @fivetran-jamie would you be able to remove that from this branch.

2024-05-23 20:21 UTC, fivetran-jamie commented on integration_tests/dbt_project.yml
> +    - pattern: offsite_conversion%
ah yeah i only added them locally

2024-05-23 20:33 UTC, fivetran-jamie commented on models/facebook_ads__account_report.sql
> +        {% endif %}
yeah this exact code is used in like 5 models so i think a macro is very appropriate!

2024-05-23 21:25 UTC, fivetran-jamie commented on models/facebook_ads__account_report.sql
> +        , sum(coalesce(conversion_report.conversion_value, 0)) as conversion_value
yeah, though i have actually yet to see a `null` (or even `0`) conversion value recorded in `basic_ad_actions`

the individual/passthrough values are null when representing 0 however
![image](https://github.com/fivetran/dbt_facebook_ads/assets/65564846/e93f30fa-d33b-49b8-a99c-1e81c791f6da)

2024-05-23 21:25 UTC, fivetran-jamie commented on CHANGELOG.md
> +- Updated the PR templates to align with our most up-to-date standards ([PR #43](https://github.com/fivetran/dbt_facebook_ads/pull/43)).
added a section

2024-05-23 21:25 UTC, fivetran-jamie commented on models/facebook_ads__account_report.sql
> +        {% endif %}
added

2024-05-24 14:12 UTC, fivetran-joemarkiewicz commented on models/facebook_ads__account_report.sql
> +        , sum(coalesce(conversion_report.conversion_value, 0)) as conversion_value
Thanks for confirming. Good to see we haven't seen `null` in the conversion value, but great to see we are being proactive with this logic. This looks good to me!

2024-05-28 02:44 UTC, maxtuzz commented
Great effort! Looking forward to this release.

2024-09-11 18:50 UTC, fivetran-jamie commented
FYI for anyone subscribed here, this is currently blocked. 

We are working with Engineering to ensure that the conversion monetary values (`action_values`) are included in a default report and therefore accessible to the package (currently, only the raw # of conversions are supported by the `basic_ad_actions` report).

2024-11-06 21:59 UTC, fivetran-joemarkiewicz requested changes
@fivetran-jamie great work on this PR and you're nearly there to releasing full support for conversions in our ad reporting packages!!

I have a few comments and suggestions in line. Additionally, I noticed I ran into a similar error from before where I run into an issue when trying to passthrough a default conversion value from this PR into the `facebook_ads__basic_ad_passthrough_metrics` variable. Would you be able to look into this and confirm if this is intentional or if there are some adjustments we need to make to this logic within the models. 

![image](https://github.com/user-attachments/assets/e20d500c-8e9b-4e8c-bcf6-ed54cc7dcc19)

Thanks!

2024-11-06 21:59 UTC, fivetran-joemarkiewicz commented on docs/run_results.json
Let's remove this file

2024-11-06 21:59 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_account_report.sql
> +        sum(coalesce(spend, 0)) as spend
Request to add conversions in but comment them out for this release so we may use them in future updates.

2024-11-06 21:59 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_account_report.sql
> +        sum(coalesce(spend, 0)) as spend
Same comment for other validation tests

2024-11-06 21:59 UTC, fivetran-joemarkiewicz commented on packages.yml
> +  warn-unpinned: false
Reminder to clean and swap before merge

2024-11-06 23:05 UTC, fivetran-jamie commented
> I noticed I ran into a similar error from before where I run into an issue when trying to passthrough a default conversion value from this PR into the facebook_ads__basic_ad_passthrough_metrics variable. Would you be able to look into this and confirm if this is intentional or if there are some adjustments we need to make to this logic within the models.

@fivetran-joemarkiewicz Yeah this is the expected behavior, as conversions are explicitly not included in `basic_ad` according to our [docs](https://fivetran.com/docs/connectors/applications/facebook-ads/prebuilt-reports). However, I suppose there is nothing stopping someone from adding `conversions` as a passthrough field, even if null (especially if they were using passthrough columns to add conversions to the ad_reporting models). 

To avoid duplicate column errors, we can employ the same `_c` suffix method as [ad_reporting](https://github.com/fivetran/dbt_ad_reporting/pull/122/), or we can just choose to select our version of `conversions` since any previous field was likely null

2024-11-06 23:19 UTC, fivetran-joemarkiewicz commented
> conversions are explicitly not included in basic_ad according to our [docs](https://fivetran.com/docs/connectors/applications/facebook-ads/prebuilt-reports).

Thanks for calling this out @fivetran-jamie! I was going through and stress testing so I see how I tested something that realistically should never occur. I would recommend if the conversion fields should not exist in the BASIC_AD table, then I feel comfortable giving our default value the preference and not including the `_c` field name as it will most likely be null. 

Thanks for clarifying this!

2024-11-07 20:21 UTC, fivetran-jamie commented on integration_tests/tests/consistency/consistency_account_report.sql
> +        sum(coalesce(spend, 0)) as spend
added

2024-11-07 22:39 UTC, fivetran-joemarkiewicz approved these changes
LGTM!

2024-11-12 22:36 UTC, fivetran-reneeli reviewed
Just had some questions!

2024-11-12 22:36 UTC, fivetran-reneeli commented on CHANGELOG.md
> +  - By default, the package includes only the conversion values calculated using the default attribution window set in Meta, but your report may include calculations using the other windows defined [
similarly as in source, do we want to just say what the default window is?

2024-11-12 22:36 UTC, fivetran-reneeli commented on README.md
> +By default, this package will select `clicks`, `impressions`, `cost`, and conversion `value` (using the default attribution window) from the source reporting tables (`BASIC_AD`, `BASIC_AD_ACTIONS`, a
also stating what the default is here?

2024-11-12 22:36 UTC, fivetran-reneeli commented on README.md
> +By default, this package will select `clicks`, `impressions`, `cost`, and conversion `value` (using the default attribution window) from the source reporting tables (`BASIC_AD`, `BASIC_AD_ACTIONS`, a
```suggestion
By default, this package will select `clicks`, `impressions`, `cost`, `conversion`, and conversion `value` (using the default attribution window) from the source reporting tables (`BASIC_AD`, `BASIC_AD_ACTIONS`, and `BASIC_AD_ACTION_VALUES`) to store into the output models. If you would like to pass through additional metrics to the output models, add the below configurations to your `dbt_project.yml` file. These variables allow for the pass-through fields to be aliased (`alias`) and transformed (`transform_sql`) if desired, but not required. Only the `name` of each metric field is required. Use the below format for declaring the respective pass-through variables:
```

2024-11-12 22:36 UTC, fivetran-reneeli commented on models/facebook_ads__campaign_report.sql
> +        on report.date_day = conversion_report.date_day
do we need to join by source_relation here as well?

2024-11-12 22:36 UTC, fivetran-reneeli commented on models/facebook_ads__url_report.sql
> +        on report.date_day = conversion_report.date_day
source_relation join?

2024-11-12 23:55 UTC, fivetran-jamie commented on CHANGELOG.md
> +  - By default, the package includes only the conversion values calculated using the default attribution window set in Meta, but your report may include calculations using the other windows defined [
adding link

2024-11-12 23:56 UTC, fivetran-jamie commented on models/facebook_ads__url_report.sql
> +        on report.date_day = conversion_report.date_day
doh!

2024-11-12 23:56 UTC, fivetran-jamie commented on models/facebook_ads__campaign_report.sql
> +        on report.date_day = conversion_report.date_day
jeez I can't believe I forgot these, good catch

2024-11-13 15:30 UTC, fivetran-reneeli approved these changes
LGTM

2024-11-14 19:41 UTC, merged